# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'supermarket' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'ActionButton'
pod ‘Kingfisher’,’~>1.7’
pod 'MJRefresh'
  # Pods for supermarket

end
